version: "3"
services:
  mongo:
    image: mongo:4.0-xenial
    expose:
    - 27017
    restart: always
    networks:
      - app
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  flask:
    build: 
      context: .
      dockerfile: Dockerfile
    image: flask-mongo:1.0
    container_name: flask
    depends_on:
      - mongo
    ports:
     - 80:80
    restart: always
    networks:
      - app
networks:
  app:
